version: '3.8'
services:
  sqlserver:
    build: ./sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyPassword!SqlSecret"
      ACCEPT_EULA: "Y"
  pago-api:
    build: .
    image: pago-microservice
    container_name: pago-api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=master;User Id=sa;Password=MyPassword!SqlSecret;Trusted_Connection=True;TrustServerCertificate=True;
      - Jwt__Key=123-my-clave-secreta-muy-secreta-123
      - Jwt__ValidationParameters=PagoApi123
    restart: unless-stopped