USE master;
GO
CREATE TABLE PAGOS (
    IDPAGO INT IDENTITY(10000,1) PRIMARY KEY,
    IDREMITENTE INT NOT NULL,
    IDDESTINATARIO INT NOT NULL,
    PRODUCTOSTOTAL INT NOT NULL,
    MONTOTOTAL DECIMAL(18, 2) NOT NULL,
    CONCEPTO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    AUFECHA DATETIME NOT NULL DEFAULT GETDATE(),
    AUUSUARIO VARCHAR(50) NOT NULL
);
GO
CREATE INDEX IN_PAGOS_IDPAGO ON PAGOS(IDPAGO);
GO
CREATE TABLE PRODUCTOS (
    IDPRODUCTO INT IDENTITY(1000,1) PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(18, 2) NOT NULL
);
GO
CREATE INDEX IN_PRODUCTOS_IDPRODUCTO ON PRODUCTOS(IDPRODUCTO);
GO
CREATE TABLE CLIENTES (
    IDCLIENTE INT IDENTITY(10000,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);
CREATE INDEX IN_CLIENTES_EMAIL ON CLIENTES(EMAIL);
GO
CREATE TABLE PAGOPRODUCTOS (
    IDPAGOPRODUCTO INT IDENTITY(10000,1) PRIMARY KEY,
    IDPAGO INT NOT NULL,
    IDPRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIOUNIDAD DECIMAL(18, 2) NOT NULL,

    CONSTRAINT FK_PAGOPRODUCTO_PAGO FOREIGN KEY (IDPAGO) REFERENCES PAGOS(IDPAGO),
    CONSTRAINT FK_PAGOPRODUCTO_PRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO)
);
GO
CREATE INDEX IN_PAGOPRODUCTO_IDPAGOPRODUCTO ON PAGOPRODUCTOS(IDPAGOPRODUCTO);
GO
----------------- INSERTS -----------------------
INSERT INTO CLIENTES (NOMBRE, EMAIL) VALUES
('Diana Moreno', 'diana.moreno@gmail.com'),
('Francisco Mireles', 'francisco.mireles@outlook.com'),
('Maria Garcia', 'maria.garcia@icloud.com');
GO
INSERT INTO PRODUCTOS (DESCRIPCION, PRECIO) VALUES
('Teclado mecánico', 850.00),
('Mouse inalámbrico', 450.00),
('Monitor 27 pulgadas', 3500.00),
('Laptop 15"', 12500.00);